app/shop/urls.py
from django.urls import path, include
from shop import  views

urlpatterns = [
    path('api/', include('shop.api.urls')),
    path('products/',views.product_view),
    path('products/detail', views.product_detail),

    path('products/cart/', views.cart_view,name='cart'),
]

app/tourism/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from tourism import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
# from uploader import views as uploader_views

schema_view = get_schema_view(
   openapi.Info(
      title="Group 22",
      default_version='v1',
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts_api.urls')),
    path('shop/', include('shop.urls')),
    path('crowdfund/', include('crowdfund.urls')),
    path('travelpartner/', include('travelpartner.urls')),
    path('home/',views.home_view,name='home'),

    path('home/form/',views.form,name='form_v'),
    path('flight-details/',views.flightdetails_listOfPlaces,name='flight'),
    path('flight-details-routes/',views.flightdetails_place_to_place,name='flight-routes'),
    path('hotel-details/',views.hoteldetails,name='hotels'),
    path('hotel_list/',views.hotel_list,name='list'),
    path('hotel_form/',views.hotel_search),
    path('hotel_details/',views.hotel_detail,name='hotel_d'),
]

app/travelpartner/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.authtoken.views import obtain_auth_token

router = DefaultRouter()
router.register('travelpartner', views.TravelPartnerViewSet,basename='travelpartner')


urlpatterns = [
    path('', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'), 
]

app/travelpartner/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import UploadView as uploader_views

from . import views


urlpatterns = [

    path('api/', include('travelpartner.api.urls')),
    path('',views.travelpartner,name='travel_partner_home'),
    path('details-form/',views.travelpartner_form,name='partner'),
    path('details-view/',views.view_partners,name='partners-detail'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/travelpartner/models.py
from django.conf import settings
from django.db import models


class TravelPartner(models.Model):

    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="travelpartner", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)
    destination = models.CharField(max_length=255)
    description = models.TextField()
    phone = models.CharField(max_length=255, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('partners-detail', args=[self.id])

    def __str__(self):
        return self.name

    # class TravelPartner(models.Model):

app/travelpartner/forms.py
from .models import TravelPartner
from django.forms import ModelForm

class TravelPartnerForm(ModelForm):
    class Meta:
        model=TravelPartner
        fields='__all__'
        exclude=['user']
0

app/travelpartner/api/views.py
from django.contrib.auth import get_user_model
from accounts_api.models import UserProfile
# from rest_framework.decorators import action
from rest_framework import viewsets
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from .serializers import TravelPartnerSerializer
from travelpartner.models import TravelPartner 

class TravelPartnerViewSet(viewsets.ModelViewSet):
    model = TravelPartner
    serializer_class = TravelPartnerSerializer

    def get_queryset(self,):
        user = self.request.user
        return TravelPartner.objects.filter(user=user)

    def perform_create(self, serializer):
        user=self.request.user
        serializer.save(user=user, name=user.name)

app/travelpartner/views.py
from django.shortcuts import render,redirect
from . models import TravelPartner
from . forms import TravelPartnerForm
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import TravelPartner

def travelpartner_form(request):
    if request.method=='POST':
        form=TravelPartnerForm(request.POST)
        print("hh")
        if form.is_valid():
            form=form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('partners-detail')
    else:
        form=TravelPartnerForm()
    context={'form':form}
    return render(request,'travelpartner/details_form.html',context=context)




def view_partners(request):
    list_partners=TravelPartner.objects.all()
    context={'list_partners':list_partners}
    return render(request,'travelpartner/details_view.html',context=context)



def travelpartner(request):
    if request.method=='POST':
        form=TravelPartnerForm(request.POST)
        if form.is_valid():
            form=form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('partners-detail')
    else:
        form=TravelPartnerForm()

    return render(request,'travelpartner/travel.html')



class UploadView(CreateView):
    model = TravelPartner
    fields = ['upload_file', ]
    success_url = reverse_lazy('fileupload')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['documents'] = TravelPartner.objects.all()
        return context

app/travelpartner/templates/travelpartner/details_form.html

<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
  <style>
    .card{
      position:relative;
      left:470px;
      top:50px;
      width:600px;
      height:600px;
      box-shadow:0 4px 8px 0 rgba(0,0,0,0.2);
    }
    .ruse{
      position:relative;
      top:60px;
    }
    .btn{
      position:relative;
      top:-330px;
      left:350px;
      width:110px;
      height:45px;
    }
    .form-control{
      width:240px;
    }
    .descr{
      position:relative;
      top:-300px;
      left:270px;
      width:290px;
    }
    #descrip{
      position:relative;
      top:-320px;
      left:290px;
    }
    #ph{
      position:relative;
      top:-45px;
    }
    .ph-1{
      position:relative;
      top:-40px;
    }
    .dest{
      position:relative;
      top:82px;
    }
    .deta{
      position:relative;
      left:210px;
      font-size:25px;
      font-weight:600;
    }

    .navbar{
    	font-size: .9rem;
        box-shadow: 0px 6px 8px -6px rgba(0,0,0,.9);
        height:50px;
        }

    .navbar-nav li{
        padding-right: .7rem

    }
    .nav-link {
    	font-family: 'Poppins',sans-serif;
        font-size: 14px;
        font-weight:350;

    }
    .nav-item{
    position:relative;
    top:0px;
    }

    .navbar-dark .navbar-nav .nav-link{
    	padding-top: .8rem;
    }

    .navbar-dark .navbar-nav .nav-link:active,
    .navbar-dark .navbar-nav .nav-link:hover{
    	color: white ;
    }
    .title{
        position:relative;
        top:-10px;
        left:15px;
        padding-top:10px;
        font-size:25px;
        font-weight:650;
        letter-spacing:-0.12em;
    }
    </style>
    <nav class="navbar navbar-expand-lg fixed-top">
        <span class="nav-item active pt-3">
          <span class="title">
            <span style='color: blue'>T</span>
            <span style='color: red' >R</span>
            <span style='color: orange'>A</span>
            <span style='color: blue'>V</span>
            <span style='color: green'>E</span>
            <span style='color: red'>L</span>
            <span style='color: orange'>A</span>
            <span style='color: blue'>G</span>
            <span style='color: red'>E</span>
            <span style='color: green'>N</span>
            <span style='color: orange'>C</span>
            <span style='color: blue'>Y</span>
  			 </span>
          </span>
          </a>

  			<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarResponsive">
  				<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse" id="navbarResponsive">
  				<ul class="navbar-nav ml-auto">
  					<li class="nav-item active">
  						<a href="{% url 'home' %}" class="nav-link"><strong>HOME</strong></a>
  					</li>

  					<li class="nav-item active two">
  						<a href="/shop/products" class="nav-link"><strong>SHOP</strong></a>
  					</li>

  					<li class="nav-item active four">
  						<a href="#aboutus" class="nav-link"><strong>ABOUT US</strong></a>
  					</li>
  					{% if  not user.is_authenticated %}

  					<li class="nav-item active five">
  						<a href="/account/signup" class="nav-link"><strong>SIGN UP</strong></a>
  					</li>
                  {% endif %}
                      {% if user.is_authenticated %}
                      	<li class="nav-item active six">
  						<a href="#contactus" class="nav-link"><strong>{{  email}}</strong></a>
  					</li>
                          <li class="nav-item active seven" >
  						<a href="/account/logout" class="nav-link" style="position:relative;top:-3.9px;left:-18px;font-size:17px;"><strong>Logout </strong></a>
  					</li>
                      {% endif %}
  				</ul>
  			</div>
  		</nav>
      {% for field in form %}
                    <p>
                      {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
         {% endfor %}
                    </p>
                {% endfor %}
                {% if form.non_field_errors %}
                  <div style="color: red">
                    <p>{{form.non_field_errors}}</p>
                  </div>

                {% endif %}
  <form method="POST">

    {% csrf_token %}

    <div class="card card-body">
<span class="deta">Your Details</span>

<label for="name" style="position:relative;top:40px;">Name:</label><input type="text" class="form-control" name="name" maxlength="255" required id="id_name" style="position:relative;top:38px;">

<label for="start_date" style="position:relative;top:42px;">Start date:</label><input type="date" class="form-control" name="start_date" required id="id_start_date" style="position:relative;top:40px;">

<label for="end_date" style="position:relative;top:70px;">End date:</label><input type="date" class="form-control" name="end_date" required id="id_end_date" style="position:relative;top:72px;">

<label for="destination" style="position:relative;top:80px;">Destination:</label><input type="text" class="form-control dest" name="destination" maxlength="255" required id="id_destination" >

<label for="description" id="descrip" style="position:relative;top:-140px;">Description:</label><textarea class="form-control descr" name="description" cols="40" rows="10" required id="id_description" style="position:relative;top:-120px;height:220px;">

</textarea>
 <label for="phone" id="ph">Phone:</label><input type="text" class="form-control ph-1" name="phone" maxlength="255" id="id_phone">

   <button class="btn btn-primary" type=submit style=position:relative;top:-150px;>Submit</button>
   </div>
     </form>

app/travelpartner/templates/travelpartner/details_form1.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<div class="card card-body">
    <img src="{% static '/images/buddy.jpg' %}" alt="">
</div>

<div class="container blue" id="auth">

    {% if user.is_authenticated %}
        {{ user.email }}
    {% endif %}

    {% if not user.is_authenticated %}
        <p>fsdlj</p>
    {% endif %}

</div>

<div class="card" style="margin: auto">
<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Name:</label>
        <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter Name">
    </div>
    <div class="form-group">
        <label for="start_date">Start date</label>
        <input type="date" class="form-control" id="start_date" placeholder="05/11/2020">
    </div>

    <div class="form-group">
        <label for="end_date">End date</label>
        <input type="date" class="form-control" id="end_date" placeholder="Password">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Destination</label>
        <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Destination">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Phone</label>
        <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter phone">
    </div>

    <div class="form-group">
        <label for="exampleInputEmail1">Description</label>
        <textarea class="form-control" id="name" aria-describedby="emailHelp" placeholder="Enter phone"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

app/travelpartner/templates/travelpartner/hotel_details.html
{{res}}

app/travelpartner/templates/travelpartner/travel.html
{% load static %}
{% include 'travelpartner/partial_components/navbar.html' %}


<link rel="stylesheet" href="{% static 'css/patner_dstyle.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Travel Partner</title>
    <style>
        #footer {
            color: white;
            display: block;

        }

        .footer-bottom {
            background-color: #f0f0f0;
            padding: 15px 0 20px;
        }

        .copyright > p {
            color: #666;
            font-size: 16px;
            font-weight: 500;
            margin: 0;
        }

        .box {
            width: 100px;
            height: 100px;
            color: red;
            background-color: red;
            margin: 20px;
        }

        .footer-dark {
            padding: 50px 0;
            color: white;
            background-color: #41A3FF;
        }

        .footer-dark h3 {
            margin-top: 0;
            margin-bottom: 12px;
            font-weight: 700;
            font-size: 16px;
        }

        .footer-dark ul {
            padding: 0;
            list-style: none;
            line-height: 1.6;
            font-size: 14px;
            margin-bottom: 0;
        }

        .footer-dark ul a {
            color: inherit;
            text-decoration: none;
        }

        .footer-dark ul a:hover {
            opacity: 0.8;
        }

        @media (max-width: 767px) {
            .footer-dark .item:not(.social) {
                text-align: center;
                padding-bottom: 20px;
            }
        }

        .footer-dark .item.text {
            margin-bottom: 36px;
        }

        @media (max-width: 767px) {
            .footer-dark .item.text {
                margin-bottom: 0;
            }
        }

        .footer-dark .item.text p {
            margin-bottom: 0;
        }

        .footer-dark .item.social {
            text-align: center;
        }

        @media (max-width: 991px) {
            .footer-dark .item.social {
                text-align: center;
                margin-top: 20px;
            }
        }

        .footer-dark .item.social > a {
            font-size: 20px;
            width: 36px;
            height: 36px;
            line-height: 36px;
            display: inline-block;
            text-align: center;
            border-radius: 50%;
            /* box-shadow: 0 0 0 1px rgba(255, 255, 255, 0.4); */
            margin: 0 8px;
            color: #fff;
            opacity: 0.75;
        }

        .footer-dark .item.social > a:hover {
            opacity: 1;
        }

        .footer-dark .copyright {
            text-align: center;
            padding-top: 24px;
            opacity: 0.3;
            font-size: 13px;
            margin-bottom: 0;
        }

        .pt-80 {
            padding-top: 80px;
        }

        hr {
            background-color: white;
        }

        .copyright {
            margin-bottom: 0;
            padding-bottom: 20px;
            text-align: center;
        }

        .shadow1 {
            box-shadow: 0 19px 38px rgba(0, 0, 0, 0.30), 0 15px 12px rgba(0, 0, 0, 0.22);
        }


        .banner-area1, .banner-area2 {
            display: flex;
            margin: auto;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background-color: #0f0f0f;
            height: 50vh;
            color: white;
        }

        .banner-area1 {
            background-size: cover;
            background-repeat: round;
        }

        .mlr {
            margin-left: 10%;
            margin-right: 10%;

        }

        img {
        {#background-size: cover;#} width: 80vw;
            height: 50vh;
        }

        .banner-area2 {
            background-color: #dedede;
            height: 20vh;
        }
    </style>
</head>
<body>
<div class="row mlr">
    <div class="banner-area1 col-md-12" style="background-image: url({% static 'images/Traveler-in-Thailand.jpg' %})">
        <h4>Find a Travel Partner</h4>
        <h6>Planning a trip? Want someone to share the journey with?</h6>
        <h6>Your travel companion is just a click away.</h6>
    </div>
</div>


{#<div class=" main-content1 mlr mt-5" style="margin-top: 40px;" >#}
{#   <div class="col-md-8" style="float: left">#}
{#       <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#        <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#        <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#        <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#        <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#        <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{#       <div class="row" style="display: flex">#}
{#           <div class="box" ></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#           <div class="box"></div>#}
{#       </div>#}
{##}
{#   </div>#}

{#    <div class="col-md-4" style="float:right;background-color: #282828">#}
{#        <form class="contact-form row" method="post">#}
{#                    {% csrf_token %}#}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <input type="text" class="form-control" placeholder="Campaign Title" name="title" >#}
{#                    </div>#}
{##}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <input type="number" class="form-control" placeholder="Amount funded" name="amount_funded">#}
{#                    </div>#}
{##}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <input type="number" class="form-control" placeholder="Amount goal" name="amount_goal">#}
{#                    </div>#}
{##}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <input type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="date_goal"#}
{#                               class="form-control" placeholder="Date goal... How long are you fundraising?#}
{#">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <input type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="date_finished"#}
{#                               class="form-control" placeholder="Date finished">#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                        <label></label>#}
{#                        <textarea class="form-control" rows="9" placeholder="Description..." name="description"></textarea>#}
{#                    </div>#}
{#                    <div class="col-md-4 col-md-offset-4">#}
{#                        <label></label>#}
{#                        <button type="submit" data-toggle="modal"#}
{#                                class="btn btn-primary btn-block btn-lg">Submit <i class="ion-android-arrow-forward"></i><!--data-target="#alertModal" -->#}
{#                        </button>#}
{#                    </div>#}
{#                </form>#}
{#</div>#}
{#</div>#}

{#travel partner signup#}
<section style="background-color: #282828">
    <div class="container" id="fundraising_form">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="margin-top-0 wow fadeIn animated t-v" style="visibility: visible;">Join Now</h2>
                <hr class="primary t-v">
                <p class="t-v">Sign up, create your profile and upload your photos. In just a few minutes, join one of the largest online travel partner communities.
                </p>
            </div>
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <form class="contact-form row" method="post">
                    <input type="hidden" name="csrfmiddlewaretoken"
                           value="ljIdQCZ4kxsjwjHSekO4gwKuOnnXwzrSprSabS4QBbqXavpNPczMjKPePcFK5GCz">
                    <div class="col-md-12">
                        <label></label>
                        <input type="text" class="form-control t-v" style="color:white;" placeholder="Name" name="name"
                               required id="id_name">
                    </div>

                    <div class="col-md-12">
                        <label></label>
                        <input type="text" class="form-control" placeholder="Mobile Number" name="phone" id="id_phone">
                    </div>

                    <div class="col-md-12">
                        <label></label>
                        <input type="text" class="form-control" placeholder="Destination" name="destination" required id="id_destination">
                    </div>

                    <div class="col-md-12">
                        <label></label>
                        <input type="text" onfocus="(this.type='date');" onblur="(this.type='text')"  class="form-control t-v" placeholder="Start Date" name="start_date" required
                               id="id_start_date">
                    </div>

                    <div class="col-md-12">
                        <label></label>
                        <input type="text" onfocus="(this.type='date');" onblur="(this.type='text')" required
                               id="id_end_date" name="end_date" style="color: white" class="form-control t-v"
                               placeholder="End Date">
">
                    </div>

                    <div class="col-md-12">
                        <label></label>
                        <textarea style="background-color: #282828" class="form-control t-v" rows="9"
                                 required id="id_description" placeholder="Description..." name="description"></textarea>
                    </div>
                    <div class="col-md-4 col-md-offset-4">
                        <label></label>
                        <button type="submit" data-toggle="modal" class="btn btn-primary btn-block btn-lg">Submit <i
                                class="ion-android-arrow-forward"></i><!--data-target="#alertModal" -->
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>


{#travel partner end#}
{#<div class="join_now banner-area1">#}
{#</div>#}
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Product offering</h3>
                    <ul>
                        <li><a href="#">Flights</a></li>
                        <li><a href="#">Holidays in USA</a></li>
                        <li><a href="#">Book Hotels</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Travel Agency</h3>
                    <p>
                        Praesent sed lobortis mi. Suspendisse vel placerat ligula.
                        Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam
                        quis tristique lectus. Aliquam in arcu eget velit pulvinar
                        dictum vel in justo.
                    </p>
                </div>
                <div class="col item social">
                    <a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i
                        class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a
                        href="#"><i class="icon ion-social-instagram"></i></a>
                </div>
            </div>

        </div>
    </footer>
</div>

</body>
</html>